# Generated by Django 4.2 on 2023-04-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
